name: movies
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.0.5
  flutter_modular: ^6.3.3
  flutter_secure_storage: ^9.2.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/img/


  fonts:
    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
