name: movies
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.0.5
  email_validator: ^3.0.0
  flutter_facebook_auth: ^7.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_modular: ^6.3.3
  flutter_native_splash: ^2.4.1
  flutter_secure_storage: ^9.2.1
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  image: assets/img/pelicula_logo.png
  color: "#e2e8ff"
  image_dark: assets/img/pelicula_white.png
  color_dark: "000000"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/pelicula_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/img/


  fonts:
    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
